name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
      - ".github/**"
    branches:
      - Alpha

env:
  TZ: Asia/Shanghai

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    strategy:
      matrix:
        include:
          # windows
          - name: windows-amd64-v3
            goos: windows
            goarch: amd64
            goamd64: v3
          # android
          - name: android-arm64
            goos: android
            goarch: arm64

      fail-fast: false
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - name: Set variables
        run: |
          git reset --soft HEAD~2
          VERSION=alpha-$(git rev-parse HEAD | cut -c 1-7 )
          BUILDTIME=$(date)
          echo "LDFLAGS=-X 'github.com/metacubex/mihomo/constant.Version=${VERSION}' -X 'github.com/metacubex/mihomo/constant.BuildTime=${BUILDTIME}' -w -s -buildid=" >> $GITHUB_ENV
          echo "TAGS=with_gvisor" >> $GITHUB_ENV
          sed -i 's/Mihomo Meta/Mihomo/g' main.go
        shell: bash

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.4.2
        if: ${{ contains(matrix.name, 'android') }}
        id: setup-ndk
        with:
          ndk-version: r26b
          add-to-path: false
          local-cache: false

      - name: Build
        if: ${{ !contains(matrix.name, 'android') }}
        run: |
          mkdir -p bin
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 GOAMD64=v3 go build -v -tags ${TAGS} -trimpath -ldflags "${LDFLAGS}" -o bin/clash-meta-alpha.exe

      - name: Build Android
        if: ${{ contains(matrix.name, 'android') }}
        run: |
          mkdir -p bin
          CC=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang
          CGO_ENABLED=1 CC=${CC} GOOS=android GOARCH=arm64 go build -v -tags ${TAGS} -trimpath -ldflags "${LDFLAGS}" -o bin/clash

      - name: Pack
        if: ${{ !contains(matrix.name, 'android') }}
        run: |
          cd bin && zip -r clash-${{ matrix.name }}.zip clash* && cd ..
        shell: bash

      - name: Pack Android
        if: ${{ contains(matrix.name, 'android') }}
        run: |
          cd bin && tar -czvf clash-${{ matrix.name }}.tar.gz clash* && cd ..
        shell: bash

      - name: Public
        if: ${{ !contains(matrix.name, 'android') }}
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: Prerelease-Alpha
          release_name: Prerelease-Alpha
          file: "bin/*.zip"
          prerelease: true
          overwrite: true
          file_glob: true

      - name: Public Android
        if: ${{ contains(matrix.name, 'android') }}
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: Prerelease-Alpha
          release_name: Prerelease-Alpha
          file: "bin/*.tar.gz"
          prerelease: true
          overwrite: true
          file_glob: true